openapi: 3.0.1
info:
  title: POS Registry API - swagger UI
  version: 1.3.0
servers:
- description: server
  url: https://www1.aade.gr/aadeapps3/posApi
paths:
  /rest/acquirer/fetch/contract/{tin}:
    get:
      operationId: fetchRegistryAfm
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      - explode: false
        in: path
        name: tin
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: mid
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: tid
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: iban
        required: false
        schema:
          type: string
        style: form
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch submitted contracts for specific TIN
      tags:
      - Services for acquirers
      x-accepts:
      - application/json
      - application/xml
  /rest/acquirer/upload/submit:
    post:
      operationId: uploadCsv
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            encoding:
              file:
                contentType: application/zip
                style: form
            schema:
              $ref: '#/components/schemas/SubmitMultipart'
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: 'Upload CSV file '
      tags:
      - Services for acquirers
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
      - application/xml
  /rest/acquirer/upload/validate:
    post:
      operationId: validateCsv
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            encoding:
              file:
                contentType: application/zip
                style: form
            schema:
              $ref: '#/components/schemas/SubmitMultipart'
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: 'Validate CSV file '
      tags:
      - Services for acquirers
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
      - application/xml
  /rest/common/fetch/errors/{transId}:
    get:
      operationId: fetchErrors
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      - explode: false
        in: path
        name: transId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch errors for specific upload
      tags:
      - Services for acquirers
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/common/fetch/upload/{transId}:
    get:
      operationId: fetchUpload
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      - explode: false
        in: path
        name: transId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch info for specific upload
      tags:
      - Services for acquirers
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/common/fetch/csv/{transId}:
    get:
      operationId: fetchUploadedCsv
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      - explode: false
        in: path
        name: transId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch uploaded file
      tags:
      - Services for acquirers
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/common/fetch/uploads:
    get:
      operationId: fetchUploads
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      - description: Date must be in DDMMYYYY format
        explode: true
        in: query
        name: dateFrom
        required: false
        schema:
          type: string
        style: form
      - description: Date must be in DDMMYYYY format
        explode: true
        in: query
        name: dateTo
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: uploadType
        required: false
        schema:
          enum:
          - ACQUIRER_POS
          - NSP_POS
          type: string
        style: form
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch list of uploaded files
      tags:
      - Services for acquirers
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/nsp/fetch/disputes/{period}:
    get:
      operationId: fetchDisputes
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      - description: Period must be in YYYYMM format
        explode: false
        in: path
        name: period
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch disputes from companies for specific month
      tags:
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/nsp/fetch/priority/afm:
    get:
      operationId: fetchPriorityAfm
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch TINs with POS with update priority
      tags:
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/nsp/fetch/priority/pos:
    get:
      operationId: fetchPriorityPos
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch POS with update priority
      tags:
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/nsp/fetch/pos/{tin}:
    get:
      operationId: fetchRegistryAfm_1
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      - explode: false
        in: path
        name: tin
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: mid
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: tid
        required: false
        schema:
          type: string
        style: form
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: Fetch submitted POS for specific TIN
      tags:
      - Services for NSPs
      x-accepts:
      - application/json
      - application/xml
  /rest/nsp/upload/submit:
    post:
      operationId: uploadCsv_1
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            encoding:
              file:
                contentType: application/zip
                style: form
            schema:
              $ref: '#/components/schemas/SubmitMultipart'
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: 'Upload CSV file '
      tags:
      - Services for NSPs
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
      - application/xml
  /rest/nsp/upload/validate:
    post:
      operationId: validateCsv_1
      parameters:
      - explode: false
        in: header
        name: tokenUsername
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: tokenPassword
        required: true
        schema:
          format: password
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            encoding:
              file:
                contentType: application/zip
                style: form
            schema:
              $ref: '#/components/schemas/SubmitMultipart'
      responses:
        default:
          content:
            application/xml: {}
            application/json: {}
          description: default response
      summary: 'Validate CSV file '
      tags:
      - Services for NSPs
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
      - application/xml
components:
  schemas:
    SubmitMultipart:
      properties:
        file:
          format: binary
          type: string
      type: object

